name: DigitalOceanDeploy
on:
  workflow_dispatch:
    {}
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SSH into DigitalOcean Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 64.227.151.41
          username: root
          key: ${{secrets.DO_SSH_KEY}}
          script: |
            cd /root/lec1
            git pull
            docker compose down
            docker compose build --no-cache
            docker compose up -d